language: go
services:
- docker
before_install:
- docker pull centrifugo/centrifugo
- docker run -p 8000:8000 centrifugo/centrifugo centrifugo --client_insecure
install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure
go:
  - "1.11.x"
  - "1.10.x"
  - "tip"
script: go test -v
